// Execute the actual DXC -> SPIR-V -> Metal mip-selection expression headlessly.
// Takes an MSL compute shader generated by test_texture_sampler_patch.py.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cmath>
#include <cstdio>

int main(int argc, char** argv) {
    if (argc != 2) return 2;
    @autoreleasepool {
        id<MTLDevice> device = MTLCreateSystemDefaultDevice();
        if (!device) return 3;
        NSError* error = nil;
        NSString* source = [NSString stringWithContentsOfFile:@(argv[1]) encoding:NSUTF8StringEncoding error:&error];
        if (!source) return 4;
        id<MTLLibrary> library = [device newLibraryWithSource:source options:nil error:&error];
        if (!library) { std::fprintf(stderr, "%s\n", error.description.UTF8String); return 5; }
        id<MTLFunction> function = [library newFunctionWithName:@"CSMain"];
        id<MTLComputePipelineState> pipeline = [device newComputePipelineStateWithFunction:function error:&error];
        if (!pipeline) return 6;
        const float samples[] = {0.0f, 1.0e-16f, 0.0625f, 0.25f, 1.0f, 2.0f, 4.0f, 16.0f, 256.0f, 1.0e20f};
        constexpr size_t count = sizeof(samples) / sizeof(samples[0]);
        id<MTLBuffer> input = [device newBufferWithBytes:samples length:sizeof(samples) options:MTLResourceStorageModeShared];
        id<MTLBuffer> output = [device newBufferWithLength:count * sizeof(float) * 4 options:MTLResourceStorageModeShared];
        id<MTLArgumentEncoder> arguments = [function newArgumentEncoderWithBufferIndex:0];
        id<MTLBuffer> argumentBuffer = [device newBufferWithLength:arguments.encodedLength options:MTLResourceStorageModeShared];
        [arguments setArgumentBuffer:argumentBuffer offset:0];
        [arguments setBuffer:input offset:0 atIndex:0];
        [arguments setBuffer:output offset:0 atIndex:1];
        id<MTLCommandQueue> queue = [device newCommandQueue];
        id<MTLCommandBuffer> command = [queue commandBuffer];
        id<MTLComputeCommandEncoder> encoder = [command computeCommandEncoder];
        [encoder setComputePipelineState:pipeline];
        [encoder setBuffer:argumentBuffer offset:0 atIndex:0];
        [encoder useResource:input usage:MTLResourceUsageRead];
        [encoder useResource:output usage:MTLResourceUsageWrite];
        [encoder dispatchThreads:MTLSizeMake(count, 1, 1) threadsPerThreadgroup:MTLSizeMake(1, 1, 1)];
        [encoder endEncoding];
        [command commit];
        [command waitUntilCompleted];
        if (command.status != MTLCommandBufferStatusCompleted) return 7;
        const float* result = static_cast<const float*>(output.contents);
        std::printf("[");
        for (size_t index = 0; index < count; ++index) {
            if (index) std::printf(",");
            std::printf("[");
            for (size_t value = 0; value < 4; ++value) {
                if (value) std::printf(",");
                const float number = result[index * 4 + value];
                if (std::isfinite(number)) std::printf("%.9g", number);
                else std::printf("null");
            }
            std::printf("]");
        }
        std::printf("]\n");
    }
    return 0;
}
