"""Phase 02: declare the libultra functions the runtime reimplements.

N64Recomp keeps a built-in list of libultra functions that ultramodern and
librecomp provide natively. Any of them found in the ELF is renamed to
`<name>_recomp` and delegated to the runtime instead of being recompiled --
which is exactly right, since recompiling hardware register access would fight
the runtime rather than serve it.

The generated code calls those `_recomp` names, but funcs.h only declares the
functions that were actually recompiled, so the calls land as implicit
declarations and C99 onward rejects them. Ten of them do this in Wave Race 64.

This emits a header declaring every name on that list, which the recompiler is
pointed at through the `recomp_include` config option. Declaring names that are
never called is harmless; missing one is a build error.

The list is read from the recompiler's own source, so it cannot drift from the
tool actually in use.

Run from the repository root:
    python tools/gen_reimplemented_decls.py
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "lib" / "N64ModernRuntime" / "N64Recomp" / "src" / "symbol_lists.cpp"
OUT = REPO / "RecompiledFuncs" / "reimplemented_decls.h"


def main():
    if not SOURCE.exists():
        sys.exit(f"missing {SOURCE}")

    text = SOURCE.read_text(errors="replace")

    # Three lists matter, not one. reimplemented_funcs is the obvious one, but
    # ignored_funcs and renamed_funcs also produce <name>_recomp calls in the
    # generated code -- __osPfsSelectBank and __osContRamRead come from
    # ignored_funcs, and omitting them fails the build just as surely.
    names = set()
    for list_name in ("reimplemented_funcs", "ignored_funcs", "renamed_funcs"):
        m = re.search(list_name + r"\s*\{(.*?)\n\};", text, re.S)
        if not m:
            sys.exit(f"could not locate the {list_name} list")
        found = re.findall(r'"([A-Za-z_]\w*)"', m.group(1))
        print(f"  {list_name:<22} {len(found)}")
        names.update(found)
    names = sorted(names)
    if not names:
        sys.exit("symbol lists parsed as empty")

    # Functions our own config marks `ignored` are emitted by nobody: the
    # recompiler skips them precisely because patches/ supplies them. Their
    # callers still reference them, so without a declaration the generated code
    # fails to compile exactly as the _recomp calls did. These are declared
    # under their own names rather than with a _recomp suffix.
    ours = []
    config = REPO / "recomp" / "wr64.toml"
    if config.exists():
        block = re.search(r"^ignored\s*=\s*\[(.*?)\]", config.read_text(), re.S | re.M)
        if block:
            ours = sorted(set(re.findall(r'"([A-Za-z_]\w*)"', block.group(1))))
            print(f"  {'ignored (ours)':<22} {len(ours)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* GENERATED by tools/gen_reimplemented_decls.py -- do not edit. */\n",
        "/*\n",
        " * Declarations for the libultra functions N64Recomp delegates to the\n",
        " * runtime. It renames each to <name>_recomp, but funcs.h only declares\n",
        " * functions that were recompiled, so without these the calls become\n",
        " * implicit declarations and the build fails under C99 and later.\n",
        " */\n",
        "#ifndef WR64_REIMPLEMENTED_DECLS_H\n",
        "#define WR64_REIMPLEMENTED_DECLS_H\n\n",
        '#include "recomp.h"\n\n',
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n",
    ]
    for name in names:
        lines.append(f"void {name}_recomp(uint8_t* rdram, recomp_context* ctx);\n")
    if ours:
        lines.append("\n/* Provided by patches/, marked `ignored` in recomp/wr64.toml. */\n")
        for name in ours:
            lines.append(f"void {name}(uint8_t* rdram, recomp_context* ctx);\n")
    lines += ["\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n"]

    OUT.write_text("".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  declarations: {len(names)}")


if __name__ == "__main__":
    main()
