"""Phase 02: find call targets that carry no function symbol.

N64Recomp refuses to recompile a function containing a `jal` to an address it
has no function for, which is correct -- it cannot generate a call to code it
has not translated. splat finds functions by following code it can reach, and
misses entry points reached only through calls it could not resolve statically.

Two things this has to get right, both of which inflate the count enormously if
got wrong:

  Scan only text. Each segment's section holds text *and* its data and rodata,
  so scanning the whole section decodes data as instructions and invents `jal`s.
  The linker emits <segment>_TEXT_START / _TEXT_END symbols; those bound it.

  A call is only missing if it resolves nowhere. An overlay calling into
  main_segment is perfectly normal, so a target is checked against every
  function symbol, not just the ones in its own section. The exception is a
  target inside the overlay vram window, where sections overlap and only the
  calling section's own symbols can be meant.

Output is written as splat symbol declarations, so the functions can be created
in the next ELF rather than papered over with per-function config entries.

Run from the repository root:
    python tools/jal_scan.py wr64.elf
"""

import re
from toolchain import readelf_command
import struct
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "recomp" / "jal_targets.txt"
READELF = readelf_command()

# Sections that load here overlap one another, so calls inside this window are
# only meaningful within the calling section.
OVERLAY_VRAM = 0x802C5800


def run_readelf(args, elf):
    return subprocess.run(READELF + args + [elf], capture_output=True,
                          text=True, cwd=REPO).stdout


def main():
    elf = sys.argv[1] if len(sys.argv) > 1 else "wr64.elf"
    data = (REPO / elf).read_bytes()

    sec_out = run_readelf(["-SW"], elf)
    sections = {}
    index_of = {}
    for m in re.finditer(
            r"\[\s*(\d+)\]\s+(\S+)\s+(\S+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s+([0-9a-f]+)\s+\S+\s+([A-Zx]*)",
            sec_out):
        num, name, typ, addr, off, size, flags = m.groups()
        if typ == "PROGBITS" and "X" in flags and int(size, 16):
            sections[name] = (int(addr, 16), int(off, 16), int(size, 16))
            index_of[name] = num

    sym_out = run_readelf(["-sW"], elf)
    funcs_by_section = defaultdict(set)
    all_funcs = set()
    bounds = {}
    for line in sym_out.splitlines():
        m = re.match(r"\s*\d+:\s+([0-9a-f]{8})\s+\d+\s+(\S+)\s+\S+\s+\S+\s+(\S+)\s+(\S+)$",
                     line)
        if not m:
            continue
        addr, typ, ndx, name = m.groups()
        value = int(addr, 16)
        if typ == "FUNC":
            funcs_by_section[ndx].add(value)
            all_funcs.add(value)
        b = re.fullmatch(r"(\w+)_TEXT_(START|END)", name)
        if b:
            bounds.setdefault(b.group(1), {})[b.group(2)] = value

    print(f"executable sections : {len(sections)}")
    print(f"function symbols    : {len(all_funcs)}")
    print(f"segments with text bounds: {len(bounds)}\n")

    missing = defaultdict(set)
    total_jal = 0
    unbounded = []

    for name, (addr, off, size) in sections.items():
        seg = name.lstrip(".")
        b = bounds.get(seg)
        if not b or "START" not in b or "END" not in b:
            unbounded.append(name)
            continue
        start, end = b["START"], b["END"]
        known = funcs_by_section.get(index_of[name], set())

        for pc in range(start, end, 4):
            file_off = off + (pc - addr)
            if file_off + 4 > len(data):
                break
            word = struct.unpack(">I", data[file_off:file_off + 4])[0]
            if (word >> 26) != 0x03:
                continue
            total_jal += 1
            target = ((pc + 4) & 0xF0000000) | ((word & 0x03FFFFFF) << 2)
            if target >= OVERLAY_VRAM:
                ok = target in known
            else:
                ok = target in all_funcs
            if not ok:
                missing[name].add(target)

    if unbounded:
        print(f"skipped (no text bounds): {', '.join(unbounded)}\n")

    n = sum(len(v) for v in missing.values())
    print(f"jal instructions    : {total_jal}")
    print(f"unresolved targets  : {n}\n")

    for name in sorted(missing):
        targets = sorted(missing[name])
        print(f"  {name:<20} {len(targets)}   " +
              " ".join(f"0x{t:08X}" for t in targets[:4]) +
              (" ..." if len(targets) > 4 else ""))

    if n:
        lines = ["// Generated by tools/jal_scan.py: call targets with no function\n",
                 "// symbol. Declared here so the next disassembly creates real\n",
                 "// functions for them.\n\n"]
        for name in sorted(missing):
            lines.append(f"// {name}\n")
            for t in sorted(missing[name]):
                lines.append(f"func_{t:08X} = 0x{t:08X}; // type:func\n")
        OUT.write_text("".join(lines))
        print(f"\nwrote {OUT.relative_to(REPO)}")
    else:
        print("every call target resolves.")


if __name__ == "__main__":
    main()
