"""Phase 01: derive an asm-only splat config from the Rev A decomp's config.

N64Recomp needs an ELF carrying symbols and section metadata. We do not need a
matching decompilation to produce one -- an assembly-only build is enough. But
the decomp's config declares 157 subsegments as type `c`, so its generated
linker script references build/src/**.o, objects that only exist if you compile
the decompiled C with IDO. That is a large dependency to take on for something
we do not need.

This script rewrites the config so every code subsegment is type `asm`. splat
then emits assembly for the whole image and generates a linker script that
references only assembled objects, which mips-linux-gnu-as and ld can build
without IDO in the picture at all.

What is deliberately NOT converted:

  hasm  Hand-written assembly, 20 subsegments. These exist precisely because
        splat's automatic output is wrong for them -- exception handlers and
        similar code with directives the disassembler does not reproduce.
        Converting them would silently corrupt the build.

  data / rodata / bss / bin / textbin
        Not code. Unchanged.

Output goes to recomp/, is committed, and is copied next to the ROM at run
time by tools/wsl_run_splat_asmonly.sh.

Run from the repository root:
    python tools/make_asm_only_yaml.py
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: python -m pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "reference" / "wr64-decomp" / "waverace64.us.rev1.yaml"
OUTPUT = REPO / "recomp" / "wr64.us.rev1.asm.yaml"

# Written relative to the decomp checkout, which is where splat runs.
OPTION_OVERRIDES = {
    "asm_path": "asm-all/us/rev1",
    "ld_script_path": "linker_scripts/us/rev1/waverace64.asmonly.ld",
    "undefined_funcs_auto_path": "linker_scripts/us/rev1/auto-asmonly/undefined_funcs_auto.ld",
    "undefined_syms_auto_path": "linker_scripts/us/rev1/auto-asmonly/undefined_syms_auto.ld",
}

converted = 0
kept_hasm = 0


def convert_subsegments(subs):
    global converted, kept_hasm
    if not subs:
        return subs
    out = []
    for s in subs:
        if isinstance(s, list) and len(s) >= 2 and s[1] == "c":
            s = list(s)
            s[1] = "asm"
            converted += 1
        elif isinstance(s, list) and len(s) >= 2 and s[1] == "hasm":
            kept_hasm += 1
        elif isinstance(s, dict):
            if s.get("type") == "c":
                s = dict(s)
                s["type"] = "asm"
                converted += 1
            elif s.get("type") == "hasm":
                kept_hasm += 1
            if "subsegments" in s:
                s["subsegments"] = convert_subsegments(s["subsegments"])
        out.append(s)
    return out


def main():
    if not SOURCE.exists():
        sys.exit(f"missing {SOURCE}\nClone the reference decomp first.")

    config = yaml.safe_load(SOURCE.read_text())

    options = config.setdefault("options", {})
    for key, value in OPTION_OVERRIDES.items():
        options[key] = value

    # Every code subsegment becomes assembly; the C tree is then unused.
    for segment in config.get("segments", []):
        if isinstance(segment, dict) and "subsegments" in segment:
            segment["subsegments"] = convert_subsegments(segment["subsegments"])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# GENERATED by tools/make_asm_only_yaml.py -- do not edit by hand.\n"
        "#\n"
        "# Derived from the Rev A decomp's waverace64.us.rev1.yaml with every\n"
        "# `c` subsegment rewritten to `asm`, so splat emits assembly for the\n"
        "# whole image and the generated linker script references only\n"
        "# assembled objects. See the script's docstring for why `hasm`\n"
        "# subsegments are deliberately left alone.\n"
        "#\n"
        f"# Target: Wave Race 64 (USA) (Rev A), sha1 {config.get('sha1', '?')}\n"
        "\n"
    )
    OUTPUT.write_text(header + yaml.safe_dump(config, sort_keys=False, width=200))

    print(f"wrote {OUTPUT.relative_to(REPO)}")
    print(f"  c -> asm subsegments converted : {converted}")
    print(f"  hasm subsegments left alone    : {kept_hasm}")
    for key, value in OPTION_OVERRIDES.items():
        print(f"  {key:<26} = {value}")


if __name__ == "__main__":
    main()
