// Wave Race 64: Recompiled -- entry point.
//
// Phase 03. This registers the game with librecomp, supplies the platform
// callbacks ultramodern needs, and starts the runtime. The recompiled game code
// is reached through recomp_entrypoint, which N64Recomp generated.
//
// The --identify path from phase 00 is kept: it is how a dump is checked
// against the pinned target before anything else is attempted.

#include "wr64/callbacks.h"
#include "wr64/crash_handler.h"
#include "wr64/renderer.h"
#include "wr64/rom.h"

#include <cstdio>
#include <filesystem>
#include <string>
#include <vector>

#include <librecomp/game.hpp>
#include <ultramodern/ultramodern.hpp>

// Generated by N64Recomp: the translated entry point of the cartridge.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

namespace {

// The phase 03 gate is that the runtime reaches the recompiled entry point and
// runs the game's first thread. Both are observable only from inside the
// runtime, so librecomp's hooks report them rather than leaving the gate to be
// inferred from the process not crashing.
void on_init(uint8_t* rdram, recomp_context* ctx) {
    (void)ctx;
    // Printing the RDRAM base makes a crash report readable: MEM_W subtracts the
    // KSEG0 base without masking, so a faulting address is only interpretable
    // relative to this. librecomp deliberately leaves guard pages around RDRAM
    // to turn a bad game pointer into an immediate fault rather than silent
    // corruption, which is why these are worth reading rather than suppressing.
    std::printf("[wr64] runtime initialised; entering recomp_entrypoint\n");
    std::printf("[wr64] rdram base = %p\n", static_cast<void*>(rdram));
    std::fflush(stdout);
}

void on_thread_create(uint8_t* rdram, recomp_context* ctx) {
    (void)rdram;
    static int count = 0;
    std::printf("[wr64] game thread %d created (entry 0x%08X)\n",
                ++count, static_cast<uint32_t>(ctx->r4));
    std::fflush(stdout);
}

// XXH3-64 of the pinned dump, which is the identity librecomp checks. Its sha1
// and header CRC are recorded in include/wr64/rom.h; this is the same dump.
constexpr uint64_t kRomHash = 0x2B675E2250A604FCULL;

constexpr char8_t kGameId[] = u8"wr64.us.rev1";

void print_usage(const char* argv0) {
    std::printf(
        "Wave Race 64: Recompiled\n"
        "\n"
        "Usage:\n"
        "  %s <rom.z64>              Run the game with the given dump\n"
        "  %s --identify <rom.z64>   Print header fields and verify the dump\n"
        "  %s --version              Print build configuration\n"
        "\n"
        "This program contains no game data. Supply your own legally obtained\n"
        "Wave Race 64 (USA) (Rev A) dump.\n",
        argv0, argv0, argv0);
}

void print_version() {
    std::printf("Wave Race 64: Recompiled -- phase 03\n");
    std::printf("  recompiled game code : %s\n",
#if WR64_WITH_RECOMPILED
        "linked");
#else
        "not built (configure with -DWR64_WITH_RECOMPILED=ON)");
#endif
    std::printf("  runtime + RT64       : %s\n",
#if WR64_WITH_RUNTIME
        "linked");
#else
        "not built (configure with -DWR64_WITH_RUNTIME=ON)");
#endif
#if WR64_WITH_RECOMPILED
    std::printf("  code sections        : %zu\n", wr64::code_section_count());
    std::printf("  overlay sections     : %zu\n", wr64::overlay_section_count());
#endif
}

int identify(const char* path) {
    wr64::RomHeader header;
    std::string error;

    if (!wr64::read_header(path, header, error)) {
        std::fprintf(stderr, "error: %s\n", error.c_str());
        return 1;
    }

    std::printf("%-16s %s\n", "file",     path);
    std::printf("%-16s %s\n", "format",   wr64::to_string(header.format).c_str());
    std::printf("%-16s %llu bytes\n", "size",
                static_cast<unsigned long long>(header.size_bytes));
    std::printf("%-16s %s\n", "name",     header.internal_name.c_str());
    std::printf("%-16s %s\n", "cart id",  header.cartridge_id.c_str());
    std::printf("%-16s %c\n", "region",   header.region ? header.region : '?');
    std::printf("%-16s %u\n", "revision", header.revision);
    std::printf("%-16s 0x%08X 0x%08X\n", "header crc", header.crc1, header.crc2);

    std::vector<std::string> problems;
    if (wr64::verify(header, problems)) {
        std::printf("\nThis dump matches the pinned target.\n");
        return 0;
    }

    std::printf("\nThis dump does NOT match the pinned target:\n");
    for (const std::string& problem : problems) {
        std::printf("  - %s\n", problem.c_str());
    }
    return 2;
}

#if WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED

int run(int argc, char** argv, const char* rom_path) {
    // Refuse a wrong dump here rather than letting it fail confusingly later.
    wr64::RomHeader header;
    std::string error;
    if (!wr64::read_header(rom_path, header, error)) {
        std::fprintf(stderr, "error: %s\n", error.c_str());
        return 1;
    }
    std::vector<std::string> problems;
    if (!wr64::verify(header, problems)) {
        std::fprintf(stderr, "This dump does not match the pinned target:\n");
        for (const std::string& problem : problems) {
            std::fprintf(stderr, "  - %s\n", problem.c_str());
        }
        return 2;
    }

    // The generated section tables have to reach librecomp before anything can
    // resolve an address, so this comes first.
    wr64::register_overlays();

    recomp::GameEntry game{};
    game.rom_hash = kRomHash;
    game.internal_name = "WAVE RACE 64";
    game.display_name = "Wave Race 64";
    game.game_id = kGameId;
    game.mod_game_id = "wr64";
    // Wave Race 64 saves records and ghost data to a 4 Kbit EEPROM.
    game.save_type = recomp::SaveType::Eep4k;
    game.is_enabled = true;
    game.entrypoint_address = static_cast<gpr>(static_cast<int32_t>(0x80046800));
    game.entrypoint = recomp_entrypoint;
    game.on_init_callback = on_init;
    game.thread_create_callback = on_thread_create;

    if (!recomp::register_game(game)) {
        std::fprintf(stderr, "error: failed to register the game with librecomp\n");
        return 1;
    }

    const recomp::RomValidationError rom_error =
        recomp::select_rom(std::filesystem::path{rom_path}, std::u8string{kGameId});
    if (rom_error != recomp::RomValidationError::Good) {
        std::fprintf(stderr, "error: librecomp rejected the dump (%d)\n",
                     static_cast<int>(rom_error));
        return 2;
    }

    recomp::Configuration config{};
    config.argc = argc;
    config.argv = argv;
    config.project_version = recomp::Version{0, 3, 0, "-phase03"};
    config.rsp_callbacks = wr64::rsp_callbacks();
    config.renderer_callbacks = wr64::renderer_callbacks();
    config.audio_callbacks = wr64::audio_callbacks();
    config.input_callbacks = wr64::input_callbacks();
    config.gfx_callbacks = wr64::gfx_callbacks();
    config.events_callbacks = wr64::events_callbacks();
    config.error_handling_callbacks = wr64::error_handling_callbacks();
    config.threads_callbacks = wr64::threads_callbacks();

    // Leave window_handle default. recomp::start() calls create_gfx and
    // create_window itself when none is supplied, and doing it here as well
    // would initialise SDL twice.

    // This has to come before start(), not after. start() spawns the game
    // thread, which then spins in wait_for_game_started, and only afterwards
    // enters its own main loop -- which does not return until the user quits.
    // Calling start_game() after it therefore never runs, and the game thread
    // waits forever for a start that has already been overtaken: the process
    // stays alive with a window open and never reaches the entry point.
    recomp::start_game(std::u8string{kGameId}, std::string{});

    recomp::start(config);
    std::fprintf(stderr, "[wr64] recomp::start returned -- runtime shut down\n");
    std::fflush(stderr);

    wr64::shutdown_platform();
    return 0;
}

#endif  // WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED

}  // namespace

int main(int argc, char** argv) {
    wr64::install_crash_handler();

    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    const std::string command = argv[1];

    if (command == "--version" || command == "-v") {
        print_version();
        return 0;
    }

    if (command == "--identify") {
        if (argc < 3) {
            std::fprintf(stderr, "error: --identify needs a path to a .z64 dump\n");
            return 1;
        }
        return identify(argv[2]);
    }

    if (!command.empty() && command[0] == '-') {
        print_usage(argv[0]);
        return 1;
    }

#if WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED
    return run(argc, argv, argv[1]);
#else
    std::fprintf(stderr,
                 "This build cannot run the game. Configure with\n"
                 "  -DWR64_WITH_RUNTIME=ON -DWR64_WITH_RECOMPILED=ON\n");
    return 1;
#endif
}
