// Wave Race 64: Recompiled -- entry point.
//
// Phase 03. This registers the game with librecomp, supplies the platform
// callbacks ultramodern needs, and starts the runtime. The recompiled game code
// is reached through recomp_entrypoint, which N64Recomp generated.
//
// The --identify path from phase 00 is kept: it is how a dump is checked
// against the pinned target before anything else is attempted.

#include "wr64/callbacks.h"
#include "wr64/crash_handler.h"
#include "wr64/renderer.h"
#include "wr64/rom.h"
#include "wr64/testdrive.h"
#if WR64_WITH_FRONTEND
#   include "wr64/frontend.h"
#endif

#include <cstdio>
#include <cstdlib>
#if defined(_WIN32)
#   include <crtdbg.h>
#   include <io.h>
#   define WIN32_LEAN_AND_MEAN
#   include <windows.h>
#endif
#include <filesystem>
#include <string>
#include <system_error>
#include <vector>

#include <librecomp/game.hpp>
#include <ultramodern/ultramodern.hpp>

// Generated by N64Recomp: the translated entry point of the cartridge.
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

namespace wr64 {

// The per-user directory for settings, controller profiles and mod state.
//
// On Windows this is %LOCALAPPDATA%\WaveRace64Recomp, the same folder RT64
// already keeps its own files in, so a player has one place to look; elsewhere
// it is $XDG_DATA_HOME/WaveRace64Recomp, or ~/.local/share/WaveRace64Recomp.
// A file called portable.txt in the working directory keeps everything there
// instead, for a copy carried on a stick -- the same convention RecompFrontend
// uses for its own paths.
std::filesystem::path settings_directory() {
    if (std::filesystem::exists("portable.txt")) {
        return std::filesystem::current_path();
    }
    const char* base = nullptr;
    std::filesystem::path root;
#if defined(_WIN32)
    base = std::getenv("LOCALAPPDATA");
    if (base != nullptr) {
        root = base;
    }
#else
    base = std::getenv("XDG_DATA_HOME");
    if (base != nullptr && *base != '\0') {
        root = base;
    }
    else if ((base = std::getenv("HOME")) != nullptr) {
        root = std::filesystem::path{ base } / ".local" / "share";
    }
#endif
    if (root.empty()) {
        return std::filesystem::current_path();
    }
    return root / "WaveRace64Recomp";
}

// The directory the executable is in, or empty if it cannot be found.
std::filesystem::path executable_directory(const char* argv0) {
    std::error_code ec;
#if defined(_WIN32)
    wchar_t buffer[MAX_PATH * 4];
    const DWORD length = GetModuleFileNameW(nullptr, buffer, static_cast<DWORD>(std::size(buffer)));
    if (length > 0 && length < std::size(buffer)) {
        return std::filesystem::path{ buffer }.parent_path();
    }
#else
    const std::filesystem::path self = std::filesystem::read_symlink("/proc/self/exe", ec);
    if (!ec) {
        return self.parent_path();
    }
#endif
    const std::filesystem::path from_argv = std::filesystem::absolute(argv0, ec);
    return ec ? std::filesystem::path{} : from_argv.parent_path();
}

}  // namespace wr64

namespace {

// The working directory the program was started from, kept so that a relative
// path on the command line still means what the user meant after the working
// directory is moved to the executable's (see main).
std::filesystem::path g_original_cwd;

std::string resolve_input_path(const char* path) {
    std::filesystem::path p{ path };
    if (p.is_relative() && !g_original_cwd.empty()) {
        p = g_original_cwd / p;
    }
    return p.string();
}

// The phase 03 gate is that the runtime reaches the recompiled entry point and
// runs the game's first thread. Both are observable only from inside the
// runtime, so librecomp's hooks report them rather than leaving the gate to be
// inferred from the process not crashing.
void on_init(uint8_t* rdram, recomp_context* ctx) {
    (void)ctx;
    // Printing the RDRAM base makes a crash report readable: MEM_W subtracts the
    // KSEG0 base without masking, so a faulting address is only interpretable
    // relative to this. librecomp deliberately leaves guard pages around RDRAM
    // to turn a bad game pointer into an immediate fault rather than silent
    // corruption, which is why these are worth reading rather than suppressing.
    std::printf("[wr64] runtime initialised; entering recomp_entrypoint\n");
    std::printf("[wr64] rdram base = %p\n", static_cast<void*>(rdram));
    std::fflush(stdout);

    // The state watcher needs the RDRAM base, and this is the first place the
    // project has it.
    wr64::set_rdram_base(rdram);

    // Must happen here rather than at startup: init_overlays() begins with
    // func_map.clear(), and librecomp calls it long before this hook.
    wr64::register_runtime_functions();
}

void on_thread_create(uint8_t* rdram, recomp_context* ctx) {
    (void)rdram;
    static int count = 0;
    std::printf("[wr64] game thread %d created (entry 0x%08X)\n",
                ++count, static_cast<uint32_t>(ctx->r4));
    std::fflush(stdout);
}

// XXH3-64 of the pinned dump, which is the identity librecomp checks. Its sha1
// and header CRC are recorded in include/wr64/rom.h; this is the same dump.


void print_usage(const char* argv0) {
    std::printf(
        "Wave Race 64: Recompiled\n"
        "\n"
        "Usage:\n"
        "  %s <rom.z64>              Run the game with the given dump\n"
        "  %s --identify <rom.z64>   Print header fields and verify the dump\n"
        "  %s --version              Print build configuration\n"
        "\n"
        "This program contains no game data. Supply your own legally obtained\n"
        "Wave Race 64 (USA) (Rev A) dump.\n",
        argv0, argv0, argv0);
}

void print_version() {
    std::printf("Wave Race 64: Recompiled 0.1.0\n");
    std::printf("  recompiled game code : %s\n",
#if WR64_WITH_RECOMPILED
        "linked");
#else
        "not built (configure with -DWR64_WITH_RECOMPILED=ON)");
#endif
    std::printf("  runtime + RT64       : %s\n",
#if WR64_WITH_RUNTIME
        "linked");
#else
        "not built (configure with -DWR64_WITH_RUNTIME=ON)");
#endif
#if WR64_WITH_RECOMPILED
    std::printf("  code sections        : %zu\n", wr64::code_section_count());
    std::printf("  overlay sections     : %zu\n", wr64::overlay_section_count());
#endif
}

int identify(const char* path_arg) {
    const std::string resolved = resolve_input_path(path_arg);
    const char* path = resolved.c_str();
    wr64::RomHeader header;
    std::string error;

    if (!wr64::read_header(path, header, error)) {
        std::fprintf(stderr, "error: %s\n", error.c_str());
        return 1;
    }

    std::printf("%-16s %s\n", "file",     path);
    std::printf("%-16s %s\n", "format",   wr64::to_string(header.format).c_str());
    std::printf("%-16s %llu bytes\n", "size",
                static_cast<unsigned long long>(header.size_bytes));
    std::printf("%-16s %s\n", "name",     header.internal_name.c_str());
    std::printf("%-16s %s\n", "cart id",  header.cartridge_id.c_str());
    std::printf("%-16s %c\n", "region",   header.region ? header.region : '?');
    std::printf("%-16s %u\n", "revision", header.revision);
    std::printf("%-16s 0x%08X 0x%08X\n", "header crc", header.crc1, header.crc2);

    std::vector<std::string> problems;
    if (wr64::verify(header, problems)) {
        std::printf("\nThis dump matches the pinned target.\n");
        return 0;
    }

    std::printf("\nThis dump does NOT match the pinned target:\n");
    for (const std::string& problem : problems) {
        std::printf("  - %s\n", problem.c_str());
    }
    return 2;
}

#if WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED

int run(int argc, char** argv, const char* rom_arg) {
    // Relative to where the user typed it, not to where main() moved us.
    const std::string rom_resolved = rom_arg != nullptr ? resolve_input_path(rom_arg) : std::string{};
    const char* rom_path = rom_arg != nullptr ? rom_resolved.c_str() : nullptr;

    // Loaded before the window opens so the script's clock starts with it.
    wr64::load_input_script();

    // Without the launcher the dump comes from the command line, so refuse a
    // wrong one here rather than letting it fail confusingly later. With the
    // launcher there may be no path at all yet: the player picks one in the UI,
    // and RecompFrontend validates it against the same hash and reports which
    // way it failed. Checking twice would only mean two error messages.
    if (rom_path != nullptr) {
        wr64::RomHeader header;
        std::string error;
        if (!wr64::read_header(rom_path, header, error)) {
            std::fprintf(stderr, "error: %s\n", error.c_str());
            return 1;
        }
        std::vector<std::string> problems;
        if (!wr64::verify(header, problems)) {
            std::fprintf(stderr, "This dump does not match the pinned target:\n");
            for (const std::string& problem : problems) {
                std::fprintf(stderr, "  - %s\n", problem.c_str());
            }
            return 2;
        }
    }


    // Where settings, controller profiles and mod state live. librecomp writes
    // them wherever it is told, and until this was added it was told nothing,
    // so they landed in the current working directory: start the game from a
    // different directory and every setting came back as its default. The
    // frontend has to see the same directory, which is why it is registered
    // here, before anything loads a setting.
    {
        const std::filesystem::path settings = wr64::settings_directory();
        std::error_code ec;
        std::filesystem::create_directories(settings, ec);
        recomp::register_config_path(settings);
        std::fprintf(stderr, "[wr64] settings directory: %s\n", settings.string().c_str());
    }

    // The generated section tables have to reach librecomp before anything can
    // resolve an address, so this comes first.
    wr64::register_overlays();

    recomp::GameEntry game{};
    game.rom_hash = wr64::kRomHash;
    game.internal_name = "WAVE RACE 64";
    game.display_name = wr64::kDisplayName;
    game.game_id = wr64::kGameId;
    game.mod_game_id = wr64::kModGameId;
    // Wave Race 64 saves records and ghost data to a 4 Kbit EEPROM.
    game.save_type = recomp::SaveType::Eep4k;
    game.is_enabled = true;
    game.entrypoint_address = static_cast<gpr>(static_cast<int32_t>(0x80046800));
    game.entrypoint = recomp_entrypoint;
    game.on_init_callback = on_init;
    game.thread_create_callback = on_thread_create;

#if WR64_WITH_FRONTEND
    wr64::frontend::publish_game(game);
#endif

    if (!recomp::register_game(game)) {
        std::fprintf(stderr, "error: failed to register the game with librecomp\n");
        return 1;
    }

    if (rom_path != nullptr) {
        const recomp::RomValidationError rom_error =
            recomp::select_rom(std::filesystem::path{rom_path}, std::u8string{wr64::kGameId});
        if (rom_error != recomp::RomValidationError::Good) {
            std::fprintf(stderr, "error: librecomp rejected the dump (%d)\n",
                         static_cast<int>(rom_error));
            return 2;
        }
    }

    recomp::Configuration config{};
    config.argc = argc;
    config.argv = argv;
    config.project_version = recomp::Version{0, 1, 0, ""};
    config.rsp_callbacks = wr64::rsp_callbacks();
#if WR64_WITH_FRONTEND
    // RecompFrontend's renderer draws the game and the menus into the same
    // command list, so it replaces the project's rather than sitting beside it.
    config.renderer_callbacks = wr64::frontend::renderer_callbacks();
#else
    config.renderer_callbacks = wr64::renderer_callbacks();
#endif
    config.audio_callbacks = wr64::audio_callbacks();
    config.input_callbacks = wr64::input_callbacks();
    config.gfx_callbacks = wr64::gfx_callbacks();
    config.events_callbacks = wr64::events_callbacks();
    config.error_handling_callbacks = wr64::error_handling_callbacks();
    config.threads_callbacks = wr64::threads_callbacks();

    // Leave window_handle default. recomp::start() calls create_gfx and
    // create_window itself when none is supplied, and doing it here as well
    // would initialise SDL twice.

    // This has to come before start(), not after. start() spawns the game
    // thread, which then spins in wait_for_game_started, and only afterwards
    // enters its own main loop -- which does not return until the user quits.
    // Calling start_game() after it therefore never runs, and the game thread
    // waits forever for a start that has already been overtaken: the process
    // stays alive with a window open and never reaches the entry point.
#if WR64_WITH_FRONTEND
    wr64::frontend::init();

    // With the launcher, the game is started from the menu -- by the player,
    // once a dump has been accepted -- so nothing is started here. A ROM given
    // on the command line still skips straight to the game, which is what the
    // scripted verification runs rely on.
    if (rom_path != nullptr) {
        recomp::start_game(std::u8string{wr64::kGameId}, std::string{});
    }
#else
    recomp::start_game(std::u8string{wr64::kGameId}, std::string{});
#endif

    recomp::start(config);
    std::fprintf(stderr, "[wr64] recomp::start returned -- runtime shut down\n");
    std::fflush(stderr);

    wr64::shutdown_platform();
    return 0;
}

#endif  // WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED

}  // namespace

int main(int argc, char** argv) {
    wr64::install_crash_handler();

#if defined(_WIN32) && !defined(NDEBUG)
    // Send failed assertions to stderr instead of a message box.
    //
    // librecomp asserts on an RSP microcode that does not end in a break. The
    // default debug-CRT behaviour is a modal dialog, which blocks the thread
    // that raised it -- and that thread is the one running RSP tasks, so the
    // game freezes exactly as if the microcode had hung, with the explanation
    // sitting in a window behind everything else. A run under a script or a
    // capture then reports a hang and no reason for it.
    _CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ASSERT, _CRTDBG_FILE_STDERR);
    _CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_FILE);
    _CrtSetReportFile(_CRT_ERROR, _CRTDBG_FILE_STDERR);
#endif

    // Unbuffer stdout. When the port's output is redirected to a file -- which
    // is how every run in this project is inspected -- stdout becomes fully
    // buffered, and the process is normally killed rather than exiting, so the
    // buffer is discarded. The recompiled RSP microcode reports unhandled jump
    // targets through printf, and those reports were being lost entirely.
    std::setvbuf(stdout, nullptr, _IONBF, 0);

    // Run from the executable's own directory, whatever directory the user
    // started it from. RecompFrontend looks for its stylesheet, fonts and icons
    // at the relative path "assets/", and on Windows that means relative to
    // the working directory. Started as build-fe\WaveRace64Recomp.exe from the
    // repository root -- the way the build instructions have always put it --
    // the launcher then failed to open its stylesheet and aborted before it
    // drew anything. The original directory is remembered so that a dump given
    // as a relative path still resolves against it.
    {
        std::error_code ec;
        g_original_cwd = std::filesystem::current_path(ec);
        const std::filesystem::path exe_dir = wr64::executable_directory(argv[0]);
        if (!exe_dir.empty()) {
            std::filesystem::current_path(exe_dir, ec);
            if (ec) {
                std::fprintf(stderr, "[wr64] could not change to %s: %s\n",
                             exe_dir.string().c_str(), ec.message().c_str());
            }
        }
    }

#if defined(_WIN32)
    // Double-clicked, the program is a console application with no one at the
    // console: Windows opens a black window beside the game for output nobody
    // asked to see. If this process is the only one attached to its console,
    // the console was created for it -- nobody typed the command -- so it is
    // released, and everything the port prints goes to wr64.log in the settings
    // directory instead. That file is what to attach to a bug report: the
    // state transcript, the frame-rate lines and any crash report all land in
    // it. Started from a shell, or with output redirected, nothing changes.
    //
    // The file is opened once, for stdout, and stderr is pointed at the same
    // descriptor. Opening it a second time for stderr fails: freopen_s opens
    // without sharing, so the second open is refused with EACCES -- and a
    // failed freopen_s leaves the stream closed, so the port's first message
    // to stderr then hit a closed stream, which the C runtime treats as a
    // fatal invalid parameter (exit 0xC0000409, before the window ever opened).
    // The redirection also happens before the console is released, while the
    // old handles are still valid to close.
    {
        DWORD owners[2];
        if (GetConsoleWindow() != nullptr && GetConsoleProcessList(owners, 2) == 1) {
            const std::filesystem::path log = wr64::settings_directory() / "wr64.log";
            std::error_code ec;
            std::filesystem::create_directories(log.parent_path(), ec);
            FILE* out = nullptr;
            bool redirected = freopen_s(&out, log.string().c_str(), "w", stdout) == 0;
            if (redirected) {
                redirected = _dup2(_fileno(stdout), _fileno(stderr)) == 0;
            }
            else {
                // Keep both streams valid whatever happens; output is lost, the
                // game is not.
                freopen_s(&out, "NUL", "w", stdout);
            }
            FreeConsole();
            std::setvbuf(stdout, nullptr, _IONBF, 0);
            std::setvbuf(stderr, nullptr, _IONBF, 0);
            if (redirected) {
                std::fprintf(stderr, "[wr64] output goes to this file when the game is started"
                                     " without a terminal\n");
            }
        }
    }
#endif

#if WR64_WITH_FRONTEND && WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED
    // With the launcher, no arguments is the normal way to start: the player
    // picks their dump in the UI. A path is still accepted and still goes
    // straight to the game, which is what the scripted verification runs use.
    if (argc < 2) {
        return run(argc, argv, nullptr);
    }
#else
    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }
#endif

    const std::string command = argv[1];

    if (command == "--version" || command == "-v") {
        print_version();
        return 0;
    }

    if (command == "--identify") {
        if (argc < 3) {
            std::fprintf(stderr, "error: --identify needs a path to a .z64 dump\n");
            return 1;
        }
        return identify(argv[2]);
    }

    if (!command.empty() && command[0] == '-') {
        print_usage(argv[0]);
        return 1;
    }

#if WR64_WITH_RUNTIME && WR64_WITH_RECOMPILED
    return run(argc, argv, argv[1]);
#else
    std::fprintf(stderr,
                 "This build cannot run the game. Configure with\n"
                 "  -DWR64_WITH_RUNTIME=ON -DWR64_WITH_RECOMPILED=ON\n");
    return 1;
#endif
}
